apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devops-test
  name: controller-manager
  namespace: {{ include "nm.namespaceOverride" . }}
