apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devops-test
    control-plane: controller-manager
  name: devops-test-controller-manager-metrics-service
  namespace: {{ include "nm.namespaceOverride" . }} 
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
