# Default values for myreplicaset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespaceOverride: "devops-test-system"

global:
  imageRegistry: ""
  nodeSelector: {}
imageRegistryOverride: ""
# value of mytest-memcached
operator:
  containers:
    operator:
      image:
        repo: swr.cn-north-4.myhuaweicloud.com/stathe/myreplicaset
        tag: v1.0.0
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}